# Generated by Django 5.2.13 on 2026-05-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_password_users_username_alter_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_gallery', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
