# Generated by Django 5.2.13 on 2026-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='user_profile_image',
            field=models.ImageField(default='n/a', upload_to='images/'),
            preserve_default=False,
        ),
    ]
