# Generated by Django 5.2.13 on 2026-05-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_alter_art_listing_seller_id'),
        ('users', '0005_remove_sellers_user_id_profile_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sellers',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
