# Generated by Django 5.2.13 on 2026-05-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_sellers_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
