# Generated by Django 5.2.13 on 2026-05-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_user_id_seller_profile_profile_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
