# Generated by Django 5.2.13 on 2026-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_seller_profile_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='is_gallery',
        ),
        migrations.AddField(
            model_name='seller',
            name='type',
            field=models.CharField(default='individual', max_length=255),
        ),
    ]
