# Generated by Django 5.2.13 on 2026-05-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_seller_user_seller_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='type',
            field=models.CharField(choices=[('Individual', 'individual'), ('Gallery', 'gallery')], max_length=255),
        ),
    ]
