# Generated by Django 5.2.13 on 2026-05-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_seller_profile_alter_seller_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='type',
            new_name='types',
        ),
    ]
