# Generated by Django 5.2.13 on 2026-05-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_type_seller_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='types',
            new_name='type',
        ),
    ]
