# Generated by Django 5.2.13 on 2026-05-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_seller_city_seller_cover_image_seller_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='rating',
        ),
    ]
