# Generated by Django 5.2.13 on 2026-05-06 12:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_sellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='art_listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('artist_name', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=255)),
                ('height_cm', models.FloatField(default=0)),
                ('width_cm', models.FloatField(default=0)),
                ('weight_kg', models.FloatField(default=0)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('date_of_creation', models.DateField(default=datetime.date.today)),
                ('starting_price', models.IntegerField(default=0)),
                ('current_bid', models.IntegerField(default=0)),
                ('mimimum_bid', models.IntegerField(default=0)),
                ('thumbnail_image_url', models.CharField(max_length=255)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sellers')),
            ],
        ),
        migrations.CreateModel(
            name='art_image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=500)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.art_listing')),
            ],
        ),
    ]
