# Generated by Django 5.2.13 on 2026-05-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_listing',
            name='date_of_creation',
        ),
        migrations.RemoveField(
            model_name='art_listing',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='art_listing',
            name='thumbnail_image_url',
        ),
        migrations.RemoveField(
            model_name='art_listing',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='art_listing',
            name='width_cm',
        ),
    ]
