# Generated by Django 5.2.13 on 2026-05-06 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_remove_art_listing_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_listing',
            name='edition',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_listing',
            name='provenance',
            field=models.TextField(default='a', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_listing',
            name='style',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_listing',
            name='year_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
