# Generated by Django 5.2.13 on 2026-05-07 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_art_listing_edition_art_listing_provenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_listing',
            name='edition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='art_listing',
            name='provenance',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='art_listing',
            name='year_created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
