# Generated by Django 5.2.13 on 2026-05-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_alter_art_listing_edition_and_more'),
        ('users', '0005_remove_sellers_user_id_profile_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_listing',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
    ]
