# Generated by Django 5.2.13 on 2026-05-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_alter_art_listing_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art_image',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='art_listing',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
