# Generated by Django 5.2.13 on 2026-05-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_rename_listing_id_art_image_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_listing',
            name='medium',
            field=models.CharField(choices=[('O', 'Oil'), ('S', 'Sculpture'), ('A', 'Acrylic'), ('W', 'Watercolour'), ('P', 'Photography')], max_length=255),
        ),
        migrations.AlterField(
            model_name='art_listing',
            name='style',
            field=models.CharField(choices=[('M', 'Modern'), ('A', 'Abstract'), ('R', 'Realism'), ('I', 'Impressionism')], max_length=255),
        ),
    ]
