# Generated by Django 5.2.13 on 2026-05-11 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_alter_art_listing_medium_alter_art_listing_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_listing',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='../static/images', verbose_name='artwork'),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='art.art_listing')),
            ],
        ),
        migrations.DeleteModel(
            name='art_image',
        ),
    ]
