# Generated by Django 5.2.13 on 2026-05-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_art_listing_thumbnail_image_listingimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_listing',
            name='dimension',
            field=models.TextField(default=30, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art_listing',
            name='medium',
            field=models.CharField(choices=[('Oil', 'Oil'), ('Sculpture', 'Sculpture'), ('Acrylic', 'Acrylic'), ('Watercolour', 'Watercolour'), ('Photography', 'Photography'), ('Digital', 'Digital')], max_length=255),
        ),
        migrations.AlterField(
            model_name='art_listing',
            name='style',
            field=models.CharField(choices=[('Modern', 'Modern'), ('Abstract', 'Abstract'), ('Realism', 'Realism'), ('Impressionism', 'Impressionism')], max_length=255),
        ),
        migrations.AlterField(
            model_name='art_listing',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='artworks/'),
        ),
    ]
