# Generated by Django 5.2.13 on 2026-05-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_art_listing_dimension_alter_art_listing_medium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art_listing',
            old_name='mimimum_bid',
            new_name='minimum_bid',
        ),
        migrations.AlterField(
            model_name='art_listing',
            name='current_bid',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
        migrations.AlterField(
            model_name='art_listing',
            name='thumbnail_image',
            field=models.ImageField(upload_to='artworks/'),
        ),
    ]
