# Generated by Django 5.2.13 on 2026-05-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_bids'),
        ('users', '0017_rename_types_seller_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
    ]
