# Generated by Django 5.2.13 on 2026-05-12 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_bid_status'),
        ('users', '0017_rename_types_seller_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Wire Transfer', 'Wire Transfer')], max_length=255)),
                ('buyer_billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='art.art_listing')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.seller')),
            ],
        ),
    ]
