# Generated by Django 5.2.13 on 2026-05-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0014_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer_nid',
            field=models.CharField(default='n/a', max_length=10),
            preserve_default=False,
        ),
    ]
