# Generated by Django 5.2.13 on 2026-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0015_sale_buyer_nid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='buyer_billing_address',
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_city',
            field=models.CharField(default='Reykjavik', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_country',
            field=models.CharField(default='Iceland', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_postal_code',
            field=models.CharField(default='101', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_street',
            field=models.CharField(default='BVatnsmýravegur 16', max_length=255),
            preserve_default=False,
        ),
    ]
