# Generated by Django 5.2.13 on 2026-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0017_alter_sale_buyer_alter_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_listing',
            name='minimum_bid',
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('wire_transfer', 'Wire Transfer')], max_length=255),
        ),
    ]
